"""Rule-based analysis of one animal's records.

None of this is generated by the language model, and that is deliberate. These
findings drive warnings a user may act on — reducing a portion, booking a vet
visit — so they have to be reproducible, explainable, and identical every time
the page is opened. A 3B model running on CPU cannot promise that.

The language model's job is to phrase answers. The arithmetic is done here.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Dict, List, Optional

from . import pets_db
from .models import Insight, Pet

# Portion guidance by brand, cups per day for a mid-size adult dog. In a real
# product this would come from the manufacturer; here it is a small lookup so
# the "fed 2.5 where the guide says 2.0" comparison has something to stand on.
PORTION_GUIDE: Dict[str, float] = {
    "acme premium": 2.0,
    "acme adult": 2.25,
    "vetline balance": 2.0,
    "naturepet complete": 2.5,
}

WEIGHT_TREND_WEEKS = 3
STOOL_WINDOW_DAYS = 30

# Beyond this fraction from target weight, say something. Applies both ways.
OVERWEIGHT_FRACTION = 0.05
# Change over the trend window that is worth flagging, in kg.
GAIN_THRESHOLD_KG = 0.5
LOSS_THRESHOLD_KG = 0.5

# Unexplained loss of this share of body weight is a clinical red flag, not a
# diet working. Treated more urgently than the equivalent gain.
RAPID_LOSS_FRACTION = 0.05

# Two consecutive weighings differing by more than this are almost certainly a
# typo rather than a real change. Saying so is more useful than computing a
# trend from bad data.
IMPLAUSIBLE_JUMP_FRACTION = 0.25


_MONTHS = {
    "tr": ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
           "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    "en": ["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"],
}


def format_date(value: date, lang: str = "en") -> str:
    """Spell out a date in the given language.

    strftime("%B") follows the system locale, which put "13 July 2026" in the
    middle of an otherwise Turkish sentence.
    """
    months = _MONTHS.get(lang, _MONTHS["en"])
    return f"{value.day} {months[value.month - 1]} {value.year}"


def portion_guidance(brand: Optional[str]) -> Optional[float]:
    """Recommended cups per day for a brand, if we know it."""
    if not brand:
        return None
    return PORTION_GUIDE.get(brand.strip().lower())


def weight_change(pet_id: int, weeks: int = WEIGHT_TREND_WEEKS) -> Optional[float]:
    """Change in kg over the last `weeks`, or None without enough history."""
    records = pets_db.weights(pet_id)
    if len(records) < 2:
        return None

    cutoff = records[-1].recorded_on - timedelta(weeks=weeks)
    earlier = [r for r in records if r.recorded_on <= cutoff]
    baseline = earlier[-1] if earlier else records[0]
    return round(records[-1].weight_kg - baseline.weight_kg, 2)


def stool_normal_ratio(pet_id: int, days: int = STOOL_WINDOW_DAYS) -> Optional[float]:
    """Fraction of recent stool records rated normal, 0.0-1.0."""
    records = pets_db.stools(pet_id, since=date.today() - timedelta(days=days))
    if not records:
        return None
    normal = sum(1 for r in records if r.quality == "normal")
    return normal / len(records)


def summary(pet: Pet) -> dict:
    """Numbers for the metric cards at the top of the insights page."""
    latest = pets_db.latest_weight(pet.id)
    feeding = pets_db.current_feeding(pet.id)
    change = weight_change(pet.id)
    ratio = stool_normal_ratio(pet.id)

    over_kg = None
    over_pct = None
    if latest and pet.target_weight_kg:
        over_kg = round(latest.weight_kg - pet.target_weight_kg, 2)
        over_pct = round(over_kg / pet.target_weight_kg * 100, 1)

    return {
        "current_weight_kg": latest.weight_kg if latest else None,
        "measured_on": latest.recorded_on.isoformat() if latest else None,
        "target_weight_kg": pet.target_weight_kg,
        "over_target_kg": over_kg,
        "over_target_pct": over_pct,
        "weight_change_kg": change,
        "weight_change_weeks": WEIGHT_TREND_WEEKS,
        "stool_normal_pct": round(ratio * 100) if ratio is not None else None,
        "food_brand": feeding.food_brand if feeding else None,
        "portion_cups": feeding.portion_cups if feeding else None,
        "recommended_cups": portion_guidance(feeding.food_brand) if feeding else None,
    }


def generate(pet: Pet) -> List[Insight]:
    """Every finding that applies to this animal right now."""
    found: List[Insight] = []
    data = summary(pet)

    # Data quality first: if the numbers are not trustworthy, say so before
    # drawing conclusions from them.
    _check_data_quality(pet, found)
    _check_weight_and_food(pet, data, found)
    _check_weight_loss(pet, data, found)
    _check_portion(data, found)
    _check_target(data, found)
    _check_stool(data, found)
    _check_missing_data(pet, data, found)

    return found


def _check_data_quality(pet: Pet, out: List[Insight]) -> None:
    """Flag weighings that cannot be real, and dates in the future."""
    records = pets_db.weights(pet.id)

    for previous, current in zip(records, records[1:]):
        if previous.weight_kg <= 0:
            continue
        jump = abs(current.weight_kg - previous.weight_kg) / previous.weight_kg
        if jump < IMPLAUSIBLE_JUMP_FRACTION:
            continue
        out.append(Insight(
            level="warning",
            title_en="A weighing looks like a typing error",
            title_tr="Bir tartım giriş hatası gibi görünüyor",
            detail_en=(
                f"{format_date(previous.recorded_on, 'en')}: "
                f"{previous.weight_kg} kg, then "
                f"{format_date(current.recorded_on, 'en')}: "
                f"{current.weight_kg} kg — a change of "
                f"{jump * 100:.0f}% between two weighings. Check the record; "
                f"the trend and the recommendations below are computed from "
                f"these numbers."
            ),
            detail_tr=(
                f"{format_date(previous.recorded_on, 'tr')}: "
                f"{previous.weight_kg} kg iken "
                f"{format_date(current.recorded_on, 'tr')}: "
                f"{current.weight_kg} kg — iki tartım arasında %{jump * 100:.0f} "
                f"değişim var. Kaydı kontrol edin; aşağıdaki trend ve öneriler "
                f"bu sayılardan hesaplanıyor."
            ),
        ))
        break  # one such warning is enough to make the point

    future = [r for r in records if r.recorded_on > date.today()]
    if future:
        latest = max(r.recorded_on for r in future)
        out.append(Insight(
            level="warning",
            title_en="A record is dated in the future",
            title_tr="İleri tarihli kayıt var",
            detail_en=(
                f"{len(future)} weighing(s) are dated after today, the latest "
                f"being {format_date(latest, 'en')}. Trends are computed from "
                f"the most recent record, so a future date distorts them."
            ),
            detail_tr=(
                f"{len(future)} tartım bugünden sonraki bir tarihe kayıtlı, en "
                f"ilerisi {format_date(latest, 'tr')}. Trendler en son kayda "
                f"göre hesaplandığı için ileri tarih sonucu bozuyor."
            ),
        ))


def _check_weight_and_food(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Rising weight, and whether it lines up with a change of food."""
    change = data["weight_change_kg"]
    if change is None or change <= GAIN_THRESHOLD_KG:
        return

    weeks = data["weight_change_weeks"]
    change_record = pets_db.last_food_change(pet.id)

    # Only claim a link if the food changed near the start of the rise.
    linked = False
    if change_record:
        latest = pets_db.latest_weight(pet.id)
        if latest:
            window_start = latest.recorded_on - timedelta(weeks=weeks + 2)
            linked = change_record.recorded_on >= window_start

    if linked and change_record:
        out.append(Insight(
            level="warning",
            title_en="Weight gain follows a change of food",
            title_tr="Kilo artışı mama değişikliğiyle örtüşüyor",
            detail_en=(
                f"Weight is up {change:+.1f} kg over the last {weeks} weeks. "
                f"The food changed to {change_record.food_brand} on "
                f"{format_date(change_record.recorded_on, 'en')}, which is "
                f"inside that window. Worth reviewing the portion."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {change:+.1f} kg arttı. Mama "
                f"{format_date(change_record.recorded_on, 'tr')} tarihinde "
                f"{change_record.food_brand} olarak değişmiş ve bu tarih söz "
                f"konusu aralığın içinde. Porsiyonun gözden geçirilmesi "
                f"yerinde olur."
            ),
        ))
    else:
        out.append(Insight(
            level="warning",
            title_en="Weight is rising",
            title_tr="Kilo artıyor",
            detail_en=(
                f"Weight is up {change:+.1f} kg over the last {weeks} weeks. "
                f"No change of food is recorded in that period, so portion size, "
                f"treats, or activity level are the places to look."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {change:+.1f} kg arttı. "
                f"Bu dönemde mama değişikliği kaydı yok; porsiyon, ödül maması "
                f"veya hareket düzeyine bakmak gerekir."
            ),
        ))


def _check_weight_loss(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Falling weight.

    Deliberately not the mirror image of the gain rule. Unexplained loss is a
    common early sign of several serious conditions, so it is reported at a
    lower bar and pointed at a vet rather than at the food bowl.
    """
    change = data["weight_change_kg"]
    current = data["current_weight_kg"]
    if change is None or change >= -LOSS_THRESHOLD_KG:
        return

    weeks = data["weight_change_weeks"]
    lost = abs(change)
    share = lost / (current + lost) if current else 0

    if share >= RAPID_LOSS_FRACTION:
        out.append(Insight(
            level="warning",
            title_en="Rapid weight loss",
            title_tr="Hızlı kilo kaybı",
            detail_en=(
                f"Weight is down {lost:.1f} kg over the last {weeks} weeks, "
                f"about {share * 100:.0f}% of body weight. Unless this is a "
                f"planned, supervised reduction, loss at this rate should be "
                f"assessed by a vet — it is an early sign of several "
                f"conditions."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {lost:.1f} kg azaldı, bu vücut "
                f"ağırlığının yaklaşık %{share * 100:.0f}'i. Planlı ve takipli "
                f"bir zayıflama değilse bu hızdaki kayıp veteriner tarafından "
                f"değerlendirilmeli — birçok hastalığın erken belirtisi."
            ),
        ))
    else:
        out.append(Insight(
            level="suggestion",
            title_en="Weight is falling",
            title_tr="Kilo düşüyor",
            detail_en=(
                f"Weight is down {lost:.1f} kg over the last {weeks} weeks. If "
                f"this is intentional, keep weighing weekly. If not, check "
                f"appetite and portion first."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {lost:.1f} kg azaldı. Bilinçli bir "
                f"zayıflamaysa haftalık tartıma devam edin. Değilse önce iştah "
                f"ve porsiyonu kontrol edin."
            ),
        ))


def _check_portion(data: dict, out: List[Insight]) -> None:
    """Portion against the manufacturer's guidance."""
    portion = data["portion_cups"]
    recommended = data["recommended_cups"]
    if portion is None or recommended is None:
        return

    difference = round(portion - recommended, 2)
    if abs(difference) < 0.25:
        return

    brand = data["food_brand"]
    if difference > 0:
        out.append(Insight(
            level="suggestion",
            title_en="Portion is above the guideline",
            title_tr="Porsiyon önerilenin üzerinde",
            detail_en=(
                f"{brand} suggests {recommended:.1f} cups a day; the record says "
                f"{portion:.1f}. Reduce gradually rather than in one step, and "
                f"weigh weekly to see the effect."
            ),
            detail_tr=(
                f"{brand} için önerilen günlük porsiyon {recommended:.1f} bardak; "
                f"kayıtta {portion:.1f} bardak görünüyor. Tek seferde değil, "
                f"kademeli olarak azaltın ve haftalık tartımla etkisini izleyin."
            ),
        ))
    else:
        out.append(Insight(
            level="suggestion",
            title_en="Portion is below the guideline",
            title_tr="Porsiyon önerilenin altında",
            detail_en=(
                f"{brand} suggests {recommended:.1f} cups a day; the record says "
                f"{portion:.1f}. If this is intentional weight management, keep "
                f"an eye on body condition."
            ),
            detail_tr=(
                f"{brand} için önerilen günlük porsiyon {recommended:.1f} bardak; "
                f"kayıtta {portion:.1f} bardak görünüyor. Kilo kontrolü için "
                f"bilinçli bir tercihse vücut kondisyonunu takip edin."
            ),
        ))


def _check_target(data: dict, out: List[Insight]) -> None:
    """Distance from the target weight."""
    over_kg = data["over_target_kg"]
    over_pct = data["over_target_pct"]
    if over_kg is None or over_pct is None:
        return

    if over_pct > OVERWEIGHT_FRACTION * 100:
        out.append(Insight(
            level="suggestion",
            title_en="Above target weight",
            title_tr="Hedef kilonun üzerinde",
            detail_en=(
                f"{over_kg:+.1f} kg above the {data['target_weight_kg']:.1f} kg "
                f"target ({over_pct:+.1f}%). Thirty minutes of walking a day "
                f"alongside a portion review is a reasonable starting point."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin {over_kg:.1f} kg "
                f"üzerinde, yani hedefin %{abs(over_pct):.1f} üstünde. Porsiyon "
                f"gözden geçirmesine ek olarak günde 30 dakika yürüyüş makul "
                f"bir başlangıç."
            ),
        ))
    elif abs(over_pct) <= OVERWEIGHT_FRACTION * 100:
        out.append(Insight(
            level="positive",
            title_en="Weight is on target",
            title_tr="Kilo hedefte",
            detail_en=(
                f"Within {OVERWEIGHT_FRACTION * 100:.0f}% of the "
                f"{data['target_weight_kg']:.1f} kg target."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin "
                f"%{OVERWEIGHT_FRACTION * 100:.0f} bandı içinde."
            ),
        ))
    else:
        out.append(Insight(
            level="warning",
            title_en="Below target weight",
            title_tr="Hedef kilonun altında",
            detail_en=(
                f"{abs(over_kg):.1f} kg below the "
                f"{data['target_weight_kg']:.1f} kg target "
                f"({abs(over_pct):.1f}% under). Being under target matters as "
                f"much as being over it; if it was not planned, have it "
                f"looked at."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin "
                f"{abs(over_kg):.1f} kg altında, yani hedefin "
                f"%{abs(over_pct):.1f} altında. Hedefin altında olmak da en az "
                f"üstünde olmak kadar önemli; planlı değilse kontrol ettirin."
            ),
        ))


def _check_stool(data: dict, out: List[Insight]) -> None:
    """Digestive health over the recent window."""
    percent = data["stool_normal_pct"]
    if percent is None:
        return

    if percent >= 90:
        out.append(Insight(
            level="positive",
            title_en="Digestion looks steady",
            title_tr="Sindirim düzenli görünüyor",
            detail_en=(
                f"{percent}% of stool records in the last {STOOL_WINDOW_DAYS} "
                f"days are normal."
            ),
            detail_tr=(
                f"Son {STOOL_WINDOW_DAYS} gündeki dışkı kayıtlarında normal "
                f"oranı %{percent}."
            ),
        ))
    elif percent < 60:
        out.append(Insight(
            level="warning",
            title_en="Stool quality is inconsistent",
            title_tr="Dışkı kalitesi düzensiz",
            detail_en=(
                f"Only {percent}% of records in the last {STOOL_WINDOW_DAYS} days "
                f"are normal. Persistent soft or loose stool is worth raising "
                f"with a vet, especially if it lasts beyond 48 hours."
            ),
            detail_tr=(
                f"Son {STOOL_WINDOW_DAYS} gündeki kayıtlarda normal oranı "
                f"yalnızca %{percent}. Süreklilik gösteren yumuşak veya sulu "
                f"dışkı, özellikle 48 saati aşıyorsa veterinere danışmayı "
                f"gerektirir."
            ),
        ))


def _check_missing_data(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Say what cannot be assessed, rather than staying silent about it."""
    if len(pets_db.weights(pet.id)) < 2:
        out.append(Insight(
            level="suggestion",
            title_en="Not enough weight history",
            title_tr="Kilo geçmişi yetersiz",
            detail_en=(
                "At least two weighings are needed before a trend can be shown. "
                "Weekly weighing gives the clearest picture."
            ),
            detail_tr=(
                "Trend gösterebilmek için en az iki tartım gerekiyor. "
                "Haftalık tartım en net tabloyu veriyor."
            ),
        ))

    if data["target_weight_kg"] is None:
        out.append(Insight(
            level="suggestion",
            title_en="No target weight set",
            title_tr="Hedef kilo tanımlı değil",
            detail_en=(
                "Setting a target weight in the profile enables the comparisons "
                "on this page. A vet can advise the right figure."
            ),
            detail_tr=(
                "Profilde hedef kilo tanımlanırsa bu sayfadaki karşılaştırmalar "
                "çalışır. Doğru değeri veteriner belirleyebilir."
            ),
        ))
