"""Rule-based analysis of one animal's records.

None of this is generated by the language model, and that is deliberate. These
findings drive warnings a user may act on — reducing a portion, booking a vet
visit — so they have to be reproducible, explainable, and identical every time
the page is opened. A 3B model running on CPU cannot promise that.

The language model's job is to phrase answers. The arithmetic is done here.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Dict, List, Optional

from . import nutrition, pets_db, vaccines
from .models import Insight, Pet

WEIGHT_TREND_WEEKS = 3
STOOL_WINDOW_DAYS = 30

# Beyond this fraction from target weight, say something. Applies both ways.
OVERWEIGHT_FRACTION = 0.05
# Change over the trend window that is worth flagging, in kg.
GAIN_THRESHOLD_KG = 0.5
LOSS_THRESHOLD_KG = 0.5

# Unexplained loss of this share of body weight is a clinical red flag, not a
# diet working. Treated more urgently than the equivalent gain.
RAPID_LOSS_FRACTION = 0.05

# Two consecutive weighings differing by more than this are almost certainly a
# typo rather than a real change. Saying so is more useful than computing a
# trend from bad data.
IMPLAUSIBLE_JUMP_FRACTION = 0.25


_MONTHS = {
    "tr": ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran",
           "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
    "en": ["January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December"],
}


def format_date(value: date, lang: str = "en") -> str:
    """Spell out a date in the given language.

    strftime("%B") follows the system locale, which put "13 July 2026" in the
    middle of an otherwise Turkish sentence.
    """
    months = _MONTHS.get(lang, _MONTHS["en"])
    return f"{value.day} {months[value.month - 1]} {value.year}"


def portion_guidance(pet: Pet) -> Optional[float]:
    """Recommended grams per day for this animal on its current food.

    Earlier this was a hardcoded table of cups per brand, which was invented.
    It is now derived: energy requirement divided by the food's energy density,
    both of which are real numbers.
    """
    analysis = nutrition.analyse(pet)
    if not analysis or not analysis.get("food"):
        return None
    return analysis["required"]["food_grams"]


def weight_change(pet_id: int, weeks: int = WEIGHT_TREND_WEEKS) -> Optional[float]:
    """Change in kg over the last `weeks`, or None without enough history."""
    records = pets_db.weights(pet_id)
    if len(records) < 2:
        return None

    cutoff = records[-1].recorded_on - timedelta(weeks=weeks)
    earlier = [r for r in records if r.recorded_on <= cutoff]
    baseline = earlier[-1] if earlier else records[0]
    return round(records[-1].weight_kg - baseline.weight_kg, 2)


def stool_normal_ratio(pet_id: int, days: int = STOOL_WINDOW_DAYS) -> Optional[float]:
    """Fraction of recent stool records rated normal, 0.0-1.0."""
    records = pets_db.stools(pet_id, since=date.today() - timedelta(days=days))
    if not records:
        return None
    normal = sum(1 for r in records if r.quality == "normal")
    return normal / len(records)


def summary(pet: Pet) -> dict:
    """Numbers for the metric cards at the top of the insights page."""
    latest = pets_db.latest_weight(pet.id)
    feeding = pets_db.current_feeding(pet.id)
    change = weight_change(pet.id)
    ratio = stool_normal_ratio(pet.id)

    over_kg = None
    over_pct = None
    if latest and pet.target_weight_kg:
        over_kg = round(latest.weight_kg - pet.target_weight_kg, 2)
        over_pct = round(over_kg / pet.target_weight_kg * 100, 1)

    analysis = nutrition.analyse(pet)
    food = analysis.get("food") if analysis else None

    return {
        "current_weight_kg": latest.weight_kg if latest else None,
        "measured_on": latest.recorded_on.isoformat() if latest else None,
        "target_weight_kg": pet.target_weight_kg,
        "over_target_kg": over_kg,
        "over_target_pct": over_pct,
        "weight_change_kg": change,
        "weight_change_weeks": WEIGHT_TREND_WEEKS,
        "stool_normal_pct": round(ratio * 100) if ratio is not None else None,
        "food_name": (food or {}).get("name") or (feeding.food_brand if feeding else None),
        "grams": feeding.grams if feeding else None,
        "recommended_grams": analysis["required"]["food_grams"] if food else None,
        "daily_kcal_need": analysis["energy"]["mer_kcal"] if analysis else None,
        "served_kcal": analysis["served"]["kcal"] if food else None,
    }


def generate(pet: Pet) -> List[Insight]:
    """Every finding that applies to this animal right now."""
    found: List[Insight] = []
    data = summary(pet)

    # Data quality first: if the numbers are not trustworthy, say so before
    # drawing conclusions from them.
    _check_data_quality(pet, found)
    _check_weight_and_food(pet, data, found)
    _check_weight_loss(pet, data, found)
    _check_portion(data, found)
    _check_macros(pet, found)
    _check_target(data, found)
    _check_stool(data, found)
    _check_vaccines(pet, found)
    _check_missing_data(pet, data, found)

    return found


def _check_vaccines(pet: Pet, out: List[Insight]) -> None:
    """Overdue and upcoming vaccinations."""
    for due in vaccines.due_list(pet):
        if due.status == "overdue" and due.core:
            late = abs(due.days_until)
            out.append(Insight(
                level="warning",
                title_en=f"{due.name_en.split('(')[0].strip()} is overdue",
                title_tr=f"{due.name_tr.split('(')[0].strip()} gecikmiş",
                detail_en=(
                    f"Due {format_date(due.due_on, 'en')}, {late} days ago. "
                    f"Protection can lapse once a booster is missed; book a "
                    f"visit and take the vaccination card."
                ),
                detail_tr=(
                    f"{format_date(due.due_on, 'tr')} tarihinde yapılmalıydı, "
                    f"{late} gün geçmiş. Rapel atlanınca koruma zayıflayabilir; "
                    f"randevu alıp aşı kartını yanınıza alın."
                ),
            ))
        elif due.status == "due_soon" and due.core:
            out.append(Insight(
                level="suggestion",
                title_en=f"{due.name_en.split('(')[0].strip()} due soon",
                title_tr=f"{due.name_tr.split('(')[0].strip()} yaklaşıyor",
                detail_en=(
                    f"Due {format_date(due.due_on, 'en')}, in "
                    f"{due.days_until} days."
                ),
                detail_tr=(
                    f"{format_date(due.due_on, 'tr')} tarihinde, "
                    f"{due.days_until} gün sonra."
                ),
            ))


def _check_data_quality(pet: Pet, out: List[Insight]) -> None:
    """Flag weighings that cannot be real, and dates in the future."""
    records = pets_db.weights(pet.id)

    for previous, current in zip(records, records[1:]):
        if previous.weight_kg <= 0:
            continue
        jump = abs(current.weight_kg - previous.weight_kg) / previous.weight_kg
        if jump < IMPLAUSIBLE_JUMP_FRACTION:
            continue
        out.append(Insight(
            level="warning",
            title_en="A weighing looks like a typing error",
            title_tr="Bir tartım giriş hatası gibi görünüyor",
            detail_en=(
                f"{format_date(previous.recorded_on, 'en')}: "
                f"{previous.weight_kg} kg, then "
                f"{format_date(current.recorded_on, 'en')}: "
                f"{current.weight_kg} kg — a change of "
                f"{jump * 100:.0f}% between two weighings. Check the record; "
                f"the trend and the recommendations below are computed from "
                f"these numbers."
            ),
            detail_tr=(
                f"{format_date(previous.recorded_on, 'tr')}: "
                f"{previous.weight_kg} kg iken "
                f"{format_date(current.recorded_on, 'tr')}: "
                f"{current.weight_kg} kg — iki tartım arasında %{jump * 100:.0f} "
                f"değişim var. Kaydı kontrol edin; aşağıdaki trend ve öneriler "
                f"bu sayılardan hesaplanıyor."
            ),
        ))
        break  # one such warning is enough to make the point

    future = [r for r in records if r.recorded_on > date.today()]
    if future:
        latest = max(r.recorded_on for r in future)
        out.append(Insight(
            level="warning",
            title_en="A record is dated in the future",
            title_tr="İleri tarihli kayıt var",
            detail_en=(
                f"{len(future)} weighing(s) are dated after today, the latest "
                f"being {format_date(latest, 'en')}. Trends are computed from "
                f"the most recent record, so a future date distorts them."
            ),
            detail_tr=(
                f"{len(future)} tartım bugünden sonraki bir tarihe kayıtlı, en "
                f"ilerisi {format_date(latest, 'tr')}. Trendler en son kayda "
                f"göre hesaplandığı için ileri tarih sonucu bozuyor."
            ),
        ))


def _check_weight_and_food(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Rising weight, and whether it lines up with a change of food."""
    change = data["weight_change_kg"]
    if change is None or change <= GAIN_THRESHOLD_KG:
        return

    weeks = data["weight_change_weeks"]
    change_record = pets_db.last_food_change(pet.id)

    # Only claim a link if the food changed near the start of the rise.
    linked = False
    if change_record:
        latest = pets_db.latest_weight(pet.id)
        if latest:
            window_start = latest.recorded_on - timedelta(weeks=weeks + 2)
            linked = change_record.recorded_on >= window_start

    if linked and change_record:
        out.append(Insight(
            level="warning",
            title_en="Weight gain follows a change of food",
            title_tr="Kilo artışı mama değişikliğiyle örtüşüyor",
            detail_en=(
                f"Weight is up {change:+.1f} kg over the last {weeks} weeks. "
                f"The food changed to {change_record.food_brand} on "
                f"{format_date(change_record.recorded_on, 'en')}, which is "
                f"inside that window. Worth reviewing the portion."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {change:+.1f} kg arttı. Mama "
                f"{format_date(change_record.recorded_on, 'tr')} tarihinde "
                f"{change_record.food_brand} olarak değişmiş ve bu tarih söz "
                f"konusu aralığın içinde. Porsiyonun gözden geçirilmesi "
                f"yerinde olur."
            ),
        ))
    else:
        out.append(Insight(
            level="warning",
            title_en="Weight is rising",
            title_tr="Kilo artıyor",
            detail_en=(
                f"Weight is up {change:+.1f} kg over the last {weeks} weeks. "
                f"No change of food is recorded in that period, so portion size, "
                f"treats, or activity level are the places to look."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {change:+.1f} kg arttı. "
                f"Bu dönemde mama değişikliği kaydı yok; porsiyon, ödül maması "
                f"veya hareket düzeyine bakmak gerekir."
            ),
        ))


def _check_weight_loss(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Falling weight.

    Deliberately not the mirror image of the gain rule. Unexplained loss is a
    common early sign of several serious conditions, so it is reported at a
    lower bar and pointed at a vet rather than at the food bowl.
    """
    change = data["weight_change_kg"]
    current = data["current_weight_kg"]
    if change is None or change >= -LOSS_THRESHOLD_KG:
        return

    weeks = data["weight_change_weeks"]
    lost = abs(change)
    share = lost / (current + lost) if current else 0

    if share >= RAPID_LOSS_FRACTION:
        out.append(Insight(
            level="warning",
            title_en="Rapid weight loss",
            title_tr="Hızlı kilo kaybı",
            detail_en=(
                f"Weight is down {lost:.1f} kg over the last {weeks} weeks, "
                f"about {share * 100:.0f}% of body weight. Unless this is a "
                f"planned, supervised reduction, loss at this rate should be "
                f"assessed by a vet — it is an early sign of several "
                f"conditions."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {lost:.1f} kg azaldı, bu vücut "
                f"ağırlığının yaklaşık %{share * 100:.0f}'i. Planlı ve takipli "
                f"bir zayıflama değilse bu hızdaki kayıp veteriner tarafından "
                f"değerlendirilmeli — birçok hastalığın erken belirtisi."
            ),
        ))
    else:
        out.append(Insight(
            level="suggestion",
            title_en="Weight is falling",
            title_tr="Kilo düşüyor",
            detail_en=(
                f"Weight is down {lost:.1f} kg over the last {weeks} weeks. If "
                f"this is intentional, keep weighing weekly. If not, check "
                f"appetite and portion first."
            ),
            detail_tr=(
                f"Son {weeks} haftada kilo {lost:.1f} kg azaldı. Bilinçli bir "
                f"zayıflamaysa haftalık tartıma devam edin. Değilse önce iştah "
                f"ve porsiyonu kontrol edin."
            ),
        ))


def _check_portion(data: dict, out: List[Insight]) -> None:
    """Portion against the animal's calculated energy requirement."""
    grams = data["grams"]
    recommended = data["recommended_grams"]
    served_kcal = data["served_kcal"]
    need_kcal = data["daily_kcal_need"]
    if grams is None or recommended is None or not need_kcal:
        return

    difference = grams - recommended
    share = abs(difference) / recommended if recommended else 0
    if share < nutrition.ENERGY_TOLERANCE:
        return

    food = data["food_name"]
    over = difference > 0
    kcal_gap = abs(served_kcal - need_kcal)

    # The calculated requirement and the scale can disagree. When they do, the
    # scale wins: it measures what happened, the formula only estimates. Telling
    # the owner of a gaining, overweight animal to feed more because a formula
    # says so would be worse than saying nothing.
    gaining = (data["weight_change_kg"] or 0) > 0
    above_target = (data["over_target_kg"] or 0) > 0

    if not over and gaining and above_target:
        out.append(Insight(
            level="warning",
            title_en="Recorded intake does not explain the weight gain",
            title_tr="Kayıtlı alım kilo artışını açıklamıyor",
            detail_en=(
                f"The record shows {grams:.0f} g of {food} a day "
                f"({served_kcal:.0f} kcal), which is below the calculated "
                f"requirement of {need_kcal:.0f} kcal — yet weight is rising "
                f"and is above target. Either something is not being recorded "
                f"(treats, scraps, a second person feeding) or the estimate is "
                f"off for this individual. Do not increase the portion on the "
                f"strength of this figure; weigh weekly and log everything the "
                f"animal eats for two weeks."
            ),
            detail_tr=(
                f"Kayıtta günde {grams:.0f} g {food} görünüyor "
                f"({served_kcal:.0f} kcal), bu hesaplanan {need_kcal:.0f} kcal "
                f"ihtiyacın altında — ama kilo artıyor ve hedefin üzerinde. "
                f"Ya kayda girmeyen bir şey var (ödül maması, sofra artığı, "
                f"başka biri besliyor) ya da tahmin bu birey için sapıyor. "
                f"Bu sayıya bakarak porsiyonu artırmayın; iki hafta boyunca "
                f"yenen her şeyi kaydedip haftalık tartın."
            ),
        ))
        return

    out.append(Insight(
        level="suggestion",
        title_en="Portion is above the calculated need" if over
                 else "Portion is below the calculated need",
        title_tr="Porsiyon hesaplanan ihtiyacın üzerinde" if over
                 else "Porsiyon hesaplanan ihtiyacın altında",
        detail_en=(
            f"{grams:.0f} g of {food} a day is {served_kcal:.0f} kcal, against a "
            f"calculated requirement of {need_kcal:.0f} kcal — "
            f"{kcal_gap:.0f} kcal {'over' if over else 'under'}, about "
            f"{recommended:.0f} g. "
            + ("Reduce gradually rather than in one step, and weigh weekly."
               if over else
               "If this is deliberate weight management, keep watching body "
               "condition; otherwise check appetite.")
        ),
        detail_tr=(
            f"Günde {grams:.0f} g {food} {served_kcal:.0f} kcal ediyor; "
            f"hesaplanan ihtiyaç {need_kcal:.0f} kcal — "
            f"{kcal_gap:.0f} kcal {'fazla' if over else 'eksik'}, yaklaşık "
            f"{recommended:.0f} g olmalı. "
            + ("Tek seferde değil kademeli azaltın ve haftalık tartın."
               if over else
               "Bilinçli bir zayıflama ise vücut kondisyonunu izleyin; "
               "değilse iştahı kontrol edin.")
        ),
    ))


def _check_macros(pet: Pet, out: List[Insight]) -> None:
    """Protein and fat against the AAFCO minimums for this life stage."""
    analysis = nutrition.analyse(pet)
    if not analysis or not analysis.get("food"):
        return

    served = analysis["served"]
    limits = analysis["minimums_dm_pct"]
    stage_en = "growth" if analysis["energy"]["life_stage"] == "growth" else "adult"
    stage_tr = "yavru" if stage_en == "growth" else "yetişkin"

    if not analysis["meets_protein_minimum"]:
        gap = abs(analysis["deltas"]["protein_g"])
        out.append(Insight(
            level="warning",
            title_en="Protein below the minimum for this life stage",
            title_tr="Protein bu yaş için minimumun altında",
            detail_en=(
                f"This food provides {served['protein_dm_pct']:.1f}% protein on a "
                f"dry matter basis; the published minimum for {stage_en} is "
                f"{limits['protein']:.1f}%. At the current amount that is about "
                f"{gap:.0f} g a day short. A complete food should meet the "
                f"minimum on its own — worth checking with a vet."
            ),
            detail_tr=(
                f"Bu mama kuru madde bazında %{served['protein_dm_pct']:.1f} "
                f"protein içeriyor; {stage_tr} için yayımlanan minimum "
                f"%{limits['protein']:.1f}. Mevcut miktarda günde yaklaşık "
                f"{gap:.0f} g eksik kalıyor. Tam mama minimumu kendi başına "
                f"karşılamalı — veterinere danışmakta fayda var."
            ),
        ))

    if not analysis["meets_fat_minimum"]:
        out.append(Insight(
            level="suggestion",
            title_en="Fat below the minimum for this life stage",
            title_tr="Yağ bu yaş için minimumun altında",
            detail_en=(
                f"{served['fat_dm_pct']:.1f}% fat on a dry matter basis against a "
                f"minimum of {limits['fat']:.1f}% for {stage_en}."
            ),
            detail_tr=(
                f"Kuru madde bazında %{served['fat_dm_pct']:.1f} yağ; "
                f"{stage_tr} için minimum %{limits['fat']:.1f}."
            ),
        ))


def _check_target(data: dict, out: List[Insight]) -> None:
    """Distance from the target weight."""
    over_kg = data["over_target_kg"]
    over_pct = data["over_target_pct"]
    if over_kg is None or over_pct is None:
        return

    if over_pct > OVERWEIGHT_FRACTION * 100:
        out.append(Insight(
            level="suggestion",
            title_en="Above target weight",
            title_tr="Hedef kilonun üzerinde",
            detail_en=(
                f"{over_kg:+.1f} kg above the {data['target_weight_kg']:.1f} kg "
                f"target ({over_pct:+.1f}%). Thirty minutes of walking a day "
                f"alongside a portion review is a reasonable starting point."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin {over_kg:.1f} kg "
                f"üzerinde, yani hedefin %{abs(over_pct):.1f} üstünde. Porsiyon "
                f"gözden geçirmesine ek olarak günde 30 dakika yürüyüş makul "
                f"bir başlangıç."
            ),
        ))
    elif abs(over_pct) <= OVERWEIGHT_FRACTION * 100:
        out.append(Insight(
            level="positive",
            title_en="Weight is on target",
            title_tr="Kilo hedefte",
            detail_en=(
                f"Within {OVERWEIGHT_FRACTION * 100:.0f}% of the "
                f"{data['target_weight_kg']:.1f} kg target."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin "
                f"%{OVERWEIGHT_FRACTION * 100:.0f} bandı içinde."
            ),
        ))
    else:
        out.append(Insight(
            level="warning",
            title_en="Below target weight",
            title_tr="Hedef kilonun altında",
            detail_en=(
                f"{abs(over_kg):.1f} kg below the "
                f"{data['target_weight_kg']:.1f} kg target "
                f"({abs(over_pct):.1f}% under). Being under target matters as "
                f"much as being over it; if it was not planned, have it "
                f"looked at."
            ),
            detail_tr=(
                f"{data['target_weight_kg']:.1f} kg hedefin "
                f"{abs(over_kg):.1f} kg altında, yani hedefin "
                f"%{abs(over_pct):.1f} altında. Hedefin altında olmak da en az "
                f"üstünde olmak kadar önemli; planlı değilse kontrol ettirin."
            ),
        ))


def _check_stool(data: dict, out: List[Insight]) -> None:
    """Digestive health over the recent window."""
    percent = data["stool_normal_pct"]
    if percent is None:
        return

    if percent >= 90:
        out.append(Insight(
            level="positive",
            title_en="Digestion looks steady",
            title_tr="Sindirim düzenli görünüyor",
            detail_en=(
                f"{percent}% of stool records in the last {STOOL_WINDOW_DAYS} "
                f"days are normal."
            ),
            detail_tr=(
                f"Son {STOOL_WINDOW_DAYS} gündeki dışkı kayıtlarında normal "
                f"oranı %{percent}."
            ),
        ))
    elif percent < 60:
        out.append(Insight(
            level="warning",
            title_en="Stool quality is inconsistent",
            title_tr="Dışkı kalitesi düzensiz",
            detail_en=(
                f"Only {percent}% of records in the last {STOOL_WINDOW_DAYS} days "
                f"are normal. Persistent soft or loose stool is worth raising "
                f"with a vet, especially if it lasts beyond 48 hours."
            ),
            detail_tr=(
                f"Son {STOOL_WINDOW_DAYS} gündeki kayıtlarda normal oranı "
                f"yalnızca %{percent}. Süreklilik gösteren yumuşak veya sulu "
                f"dışkı, özellikle 48 saati aşıyorsa veterinere danışmayı "
                f"gerektirir."
            ),
        ))


def _check_missing_data(pet: Pet, data: dict, out: List[Insight]) -> None:
    """Say what cannot be assessed, rather than staying silent about it."""
    if len(pets_db.weights(pet.id)) < 2:
        out.append(Insight(
            level="suggestion",
            title_en="Not enough weight history",
            title_tr="Kilo geçmişi yetersiz",
            detail_en=(
                "At least two weighings are needed before a trend can be shown. "
                "Weekly weighing gives the clearest picture."
            ),
            detail_tr=(
                "Trend gösterebilmek için en az iki tartım gerekiyor. "
                "Haftalık tartım en net tabloyu veriyor."
            ),
        ))

    if data["target_weight_kg"] is None:
        out.append(Insight(
            level="suggestion",
            title_en="No target weight set",
            title_tr="Hedef kilo tanımlı değil",
            detail_en=(
                "Setting a target weight in the profile enables the comparisons "
                "on this page. A vet can advise the right figure."
            ),
            detail_tr=(
                "Profilde hedef kilo tanımlanırsa bu sayfadaki karşılaştırmalar "
                "çalışır. Doğru değeri veteriner belirleyebilir."
            ),
        ))
