"""Shared data types.

This is the contract between the ingestion side (chunking, db, ingest) and
the query side (retrieve, rag, cli). Both halves import from here, so they can
be built independently as long as these shapes hold.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import List, Optional

import numpy as np


@dataclass
class Chunk:
    """A passage of a source document, with its embedding."""

    source: str          # file name, e.g. "vaccination.md"
    chunk_index: int     # position within that file, 0-based
    content: str
    embedding: Optional[np.ndarray] = None   # float32, shape (dim,)
    id: Optional[int] = None                 # set by the database


@dataclass
class Retrieved:
    """A chunk plus how well it matched the query."""

    chunk: Chunk
    score: float


@dataclass
class Answer:
    """The result of a full RAG round trip."""

    text: str
    sources: List[str] = field(default_factory=list)
    retrieved: List[Retrieved] = field(default_factory=list)
    latency_s: float = 0.0
    used_fallback: bool = False
    used_pet_record: bool = False   # True when the animal's own data fed the prompt


# --- The animal and its records ------------------------------------------
#
# The document collection is general knowledge. These types hold what is true
# of one specific animal, which is what turns "puppies need 3-4 meals a day"
# into "Bella is being fed 2.5 cups when the guide says 2.0".


@dataclass
class Pet:
    """Profile of one animal."""

    name: str
    species: str = "dog"              # "dog" | "cat"
    breed: Optional[str] = None
    birth_date: Optional[date] = None
    sex: Optional[str] = None         # "female" | "male"
    target_weight_kg: Optional[float] = None
    owner_name: Optional[str] = None
    id: Optional[int] = None

    @property
    def age_months(self) -> Optional[int]:
        if self.birth_date is None:
            return None
        today = date.today()
        return (today.year - self.birth_date.year) * 12 + today.month - self.birth_date.month

    def age_text(self, lang: str = "en") -> str:
        months = self.age_months
        if months is None:
            return "-"
        years, rest = divmod(months, 12)
        if lang == "tr":
            parts = ([f"{years} yıl"] if years else []) + ([f"{rest} ay"] if rest else [])
            return " ".join(parts) or "0 ay"
        parts = ([f"{years} yr"] if years else []) + ([f"{rest} mo"] if rest else [])
        return " ".join(parts) or "0 mo"


@dataclass
class WeightRecord:
    """One weighing."""

    pet_id: int
    recorded_on: date
    weight_kg: float
    id: Optional[int] = None


@dataclass
class FeedingRecord:
    """What the animal is being fed, as of a date.

    A new row is added when the food or the portion changes, so a change of
    brand has a date attached and can be lined up against the weight curve.
    """

    pet_id: int
    recorded_on: date
    food_brand: str
    portion_cups: float
    meals_per_day: Optional[int] = None
    note: Optional[str] = None
    id: Optional[int] = None


@dataclass
class StoolRecord:
    """Stool quality and frequency, a practical proxy for digestive health."""

    pet_id: int
    recorded_on: date
    quality: str                      # "normal" | "soft" | "loose" | "hard"
    frequency_per_day: Optional[float] = None
    id: Optional[int] = None


@dataclass
class Insight:
    """One finding produced by the rules in insights.py.

    Deliberately not generated by the language model: these drive warnings a
    user may act on, so they have to be reproducible and explainable.
    """

    level: str                        # "warning" | "positive" | "suggestion"
    title_en: str
    title_tr: str
    detail_en: str
    detail_tr: str

    def title(self, lang: str = "en") -> str:
        return self.title_tr if lang == "tr" else self.title_en

    def detail(self, lang: str = "en") -> str:
        return self.detail_tr if lang == "tr" else self.detail_en
