"""The vet report: something to print and take to an appointment.

Everything on it is either a recorded fact or a rule-based finding. No sentence
here is generated by the language model, for the same reason the insights are
not: a report a vet reads has to say the same thing every time it is produced.
"""

from __future__ import annotations

from datetime import date, datetime
from pathlib import Path
from typing import Dict, List

from . import config, insights, pets_db
from .models import Pet

REPORT_DIR = config.ROOT_DIR / "reports"

TEXT: Dict[str, Dict[str, str]] = {
    "en": {
        "title": "Veterinary Report",
        "patient": "PATIENT",
        "name": "Name",
        "species_breed": "Species / Breed",
        "age": "Age",
        "sex": "Sex",
        "owner": "Owner",
        "weight": "WEIGHT",
        "target": "Target weight",
        "current": "Current weight",
        "measured": "Last measured",
        "change": "Change over 3 weeks",
        "history": "WEIGHING HISTORY",
        "nutrition": "NUTRITION",
        "food": "Current food",
        "portion": "Daily portion",
        "recommended": "recommended",
        "meals": "Meals per day",
        "last_change": "Food last changed",
        "digestion": "DIGESTION",
        "stool_normal": "Stool normal (last 30 days)",
        "assessment": "ASSESSMENT",
        "recommendations": "RECOMMENDATIONS",
        "footer": (
            "Generated automatically by Pawprint-Local. Runs offline; data stays "
            "on the device. Findings are rule-based, not a diagnosis, and require "
            "veterinary confirmation."
        ),
        "generated": "Generated",
        "none": "No records",
        "cups": "cups",
    },
    "tr": {
        "title": "Veteriner Raporu",
        "patient": "HASTA BİLGİLERİ",
        "name": "İsim",
        "species_breed": "Tür / Irk",
        "age": "Yaş",
        "sex": "Cinsiyet",
        "owner": "Sahibi",
        "weight": "KİLO",
        "target": "Hedef kilo",
        "current": "Mevcut kilo",
        "measured": "Son ölçüm",
        "change": "3 haftalık değişim",
        "history": "TARTIM GEÇMİŞİ",
        "nutrition": "BESLENME",
        "food": "Mevcut mama",
        "portion": "Günlük porsiyon",
        "recommended": "önerilen",
        "meals": "Günlük öğün",
        "last_change": "Son mama değişikliği",
        "digestion": "SİNDİRİM",
        "stool_normal": "Normal dışkı (son 30 gün)",
        "assessment": "DEĞERLENDİRME",
        "recommendations": "ÖNERİLER",
        "footer": (
            "Pawprint-Local tarafından otomatik oluşturulmuştur. Çevrimdışı "
            "çalışır, veriler cihazda kalır. Bulgular kural tabanlıdır, teşhis "
            "değildir ve veteriner onayı gerektirir."
        ),
        "generated": "Oluşturulma",
        "none": "Kayıt yok",
        "cups": "bardak",
    },
}

SEX = {
    "en": {"female": "Female", "male": "Male"},
    "tr": {"female": "Dişi", "male": "Erkek"},
}

SPECIES = {
    "en": {"dog": "Dog", "cat": "Cat"},
    "tr": {"dog": "Köpek", "cat": "Kedi"},
}


def build(pet: Pet, lang: str = config.DEFAULT_LANGUAGE) -> dict:
    """Everything the report shows, as data. The UI and the PDF share this."""
    t = TEXT.get(lang, TEXT["en"])
    data = insights.summary(pet)
    found = insights.generate(pet)
    feeding = pets_db.current_feeding(pet.id)
    change = pets_db.last_food_change(pet.id)

    species = SPECIES.get(lang, SPECIES["en"]).get(pet.species, pet.species)
    breed = f"{species} / {pet.breed}" if pet.breed else species

    return {
        "labels": t,
        "title": t["title"],
        "generated_on": date.today().isoformat(),
        "patient": {
            "name": pet.name,
            "species_breed": breed,
            "age": pet.age_text(lang),
            "sex": SEX.get(lang, SEX["en"]).get(pet.sex or "", "-"),
            "owner": pet.owner_name or "-",
        },
        "weight": {
            "target_kg": data["target_weight_kg"],
            "current_kg": data["current_weight_kg"],
            "over_kg": data["over_target_kg"],
            "over_pct": data["over_target_pct"],
            "measured_on": data["measured_on"],
            "change_kg": data["weight_change_kg"],
            "change_weeks": data["weight_change_weeks"],
        },
        "history": [
            {"date": r.recorded_on.isoformat(), "weight_kg": r.weight_kg}
            for r in pets_db.weights(pet.id, limit=10)
        ],
        "nutrition": {
            "brand": data["food_brand"],
            "portion_cups": data["portion_cups"],
            "recommended_cups": data["recommended_cups"],
            "meals_per_day": feeding.meals_per_day if feeding else None,
            "last_change_on": change.recorded_on.isoformat() if change else None,
            "last_change_to": change.food_brand if change else None,
        },
        "digestion": {"stool_normal_pct": data["stool_normal_pct"]},
        "assessment": [
            {"level": i.level, "title": i.title(lang), "detail": i.detail(lang)}
            for i in found if i.level == "warning"
        ],
        "recommendations": [
            {"level": i.level, "title": i.title(lang), "detail": i.detail(lang)}
            for i in found if i.level != "warning"
        ],
    }


def _lines(data: dict) -> List[str]:
    """The report as plain text, which the PDF then lays out."""
    t = data["labels"]
    out: List[str] = []
    add = out.append

    patient = data["patient"]
    add(f"## {t['patient']}")
    add(f"{t['name']}|{patient['name']}")
    add(f"{t['species_breed']}|{patient['species_breed']}")
    add(f"{t['age']}|{patient['age']}")
    add(f"{t['sex']}|{patient['sex']}")
    add(f"{t['owner']}|{patient['owner']}")

    weight = data["weight"]
    add(f"## {t['weight']}")
    if weight["target_kg"] is not None:
        add(f"{t['target']}|{weight['target_kg']:.1f} kg")
    if weight["current_kg"] is not None:
        current = f"{weight['current_kg']:.1f} kg"
        if weight["over_pct"] is not None:
            current += f" ({weight['over_pct']:+.1f}%)"
        add(f"{t['current']}|{current}")
    if weight["measured_on"]:
        add(f"{t['measured']}|{weight['measured_on']}")
    if weight["change_kg"] is not None:
        add(f"{t['change']}|{weight['change_kg']:+.1f} kg")

    if data["history"]:
        add(f"## {t['history']}")
        for row in data["history"]:
            add(f"{row['date']}|{row['weight_kg']:.1f} kg")

    nutrition = data["nutrition"]
    add(f"## {t['nutrition']}")
    add(f"{t['food']}|{nutrition['brand'] or t['none']}")
    if nutrition["portion_cups"] is not None:
        portion = f"{nutrition['portion_cups']:.1f} {t['cups']}"
        if nutrition["recommended_cups"] is not None:
            portion += (f" ({t['recommended']}: "
                        f"{nutrition['recommended_cups']:.1f})")
        add(f"{t['portion']}|{portion}")
    if nutrition["meals_per_day"]:
        add(f"{t['meals']}|{nutrition['meals_per_day']}")
    if nutrition["last_change_on"]:
        add(f"{t['last_change']}|{nutrition['last_change_on']} "
            f"({nutrition['last_change_to']})")

    if data["digestion"]["stool_normal_pct"] is not None:
        add(f"## {t['digestion']}")
        add(f"{t['stool_normal']}|%{data['digestion']['stool_normal_pct']}")

    if data["assessment"]:
        add(f"## {t['assessment']}")
        for item in data["assessment"]:
            add(f">{item['detail']}")

    if data["recommendations"]:
        add(f"## {t['recommendations']}")
        for index, item in enumerate(data["recommendations"], 1):
            add(f"-{index}. {item['detail']}")

    return out


def write_pdf(pet: Pet, lang: str = config.DEFAULT_LANGUAGE) -> Path:
    """Render the report to a PDF and return its path."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    data = build(pet, lang)
    t = data["labels"]

    REPORT_DIR.mkdir(exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    path = REPORT_DIR / f"{pet.name.lower()}-{stamp}.pdf"

    page = canvas.Canvas(str(path), pagesize=A4)
    width, height = A4
    left, right = 20 * mm, width - 20 * mm
    y = height - 22 * mm

    def rule(thickness: float = 0.4) -> None:
        nonlocal y
        page.setLineWidth(thickness)
        page.setStrokeColorRGB(0.75, 0.75, 0.78)
        page.line(left, y, right, y)
        y -= 5 * mm

    def wrapped(text: str, font: str, size: float, indent: float = 0) -> None:
        nonlocal y
        page.setFont(font, size)
        words, line = text.split(), ""
        limit = right - left - indent
        for word in words:
            candidate = f"{line} {word}".strip()
            if page.stringWidth(candidate, font, size) <= limit:
                line = candidate
                continue
            page.drawString(left + indent, y, line)
            y -= size + 2.5
            line = word
        if line:
            page.drawString(left + indent, y, line)
            y -= size + 2.5

    page.setFont("Helvetica-Bold", 17)
    page.drawString(left, y, f"{t['title']} — {pet.name}")
    y -= 8 * mm
    page.setFont("Helvetica", 8.5)
    page.setFillColorRGB(0.42, 0.42, 0.45)
    page.drawString(left, y, f"{t['generated']}: {data['generated_on']}")
    page.setFillColorRGB(0, 0, 0)
    y -= 6 * mm
    rule(0.9)

    for line in _lines(data):
        if y < 34 * mm:
            page.showPage()
            y = height - 22 * mm

        if line.startswith("## "):
            y -= 3 * mm
            page.setFont("Helvetica-Bold", 10)
            page.drawString(left, y, line[3:])
            y -= 4.5 * mm
            rule()
        elif line.startswith(">"):
            wrapped(line[1:], "Helvetica-Oblique", 9.5, indent=4)
            y -= 1.5 * mm
        elif line.startswith("-"):
            wrapped(line[1:], "Helvetica", 9.5, indent=8)
        else:
            label, _, value = line.partition("|")
            page.setFont("Helvetica", 9.5)
            page.setFillColorRGB(0.35, 0.35, 0.38)
            page.drawString(left + 4, y, label)
            page.setFillColorRGB(0, 0, 0)
            page.setFont("Helvetica-Bold", 9.5)
            page.drawRightString(right - 4, y, value)
            y -= 5.6 * mm

    y = max(y, 20 * mm)
    page.setFont("Helvetica", 7.5)
    page.setFillColorRGB(0.45, 0.45, 0.48)
    for chunk in _split(t["footer"], 110):
        page.drawString(left, y, chunk)
        y -= 3.4 * mm

    page.save()
    return path


def _split(text: str, width: int) -> List[str]:
    lines, line = [], ""
    for word in text.split():
        if len(f"{line} {word}".strip()) <= width:
            line = f"{line} {word}".strip()
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines
